apiVersion: batch/v1beta1
kind: CronJob
metadata:
 name: site-changer-check
spec:
 concurrencyPolicy: Allow
 failedJobsHistoryLimit: 1
 jobTemplate:
   metadata:
     creationTimestamp: null
   spec:
     template:
       metadata:
         creationTimestamp: null
       spec:
         containers:
         - env:
            - name: URL
              value: "https://foo.bar/"
            - name: TRIGGER_WORD
              value: "WORD to be triggered"
            - name: TELEGRAM_CHAT_ID
              value: ""
            - name: TELEGRAM_API_KEY
              value: "XXXXXX:XXXXXXXXXXXXXXXXXXXXXXX"
           image: alexxanddr/site-changer-check:latest
           imagePullPolicy: Always
           name: site-changer-check
           resources: {}
           terminationMessagePath: /dev/termination-log
           terminationMessagePolicy: File
         dnsPolicy: ClusterFirst
         restartPolicy: OnFailure
         schedulerName: default-scheduler
         securityContext: {}
         terminationGracePeriodSeconds: 30
 schedule: "*/5 * * * *"
 successfulJobsHistoryLimit: 3
 suspend: false
